// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxTfsUNjKWkuaPvLUZ6fE3C-p8ew60jHg',
    appId: '1:773220965064:web:716a6418986106c72123fd',
    messagingSenderId: '773220965064',
    projectId: 'grocery-80ead',
    authDomain: 'grocery-80ead.firebaseapp.com',
    storageBucket: 'grocery-80ead.appspot.com',
    measurementId: 'G-TW6E0698CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXifnq-OxIeTNVJUVi3lPS1wY9Y2ggx6U',
    appId: '1:773220965064:android:bb64175de0bdc8d82123fd',
    messagingSenderId: '773220965064',
    projectId: 'grocery-80ead',
    storageBucket: 'grocery-80ead.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyJrC0BrNIuzt0Lk2Yu92NOgADKgYZvXk',
    appId: '1:773220965064:ios:822f0c39caf3848c2123fd',
    messagingSenderId: '773220965064',
    projectId: 'grocery-80ead',
    storageBucket: 'grocery-80ead.appspot.com',
    androidClientId: '773220965064-677sbjilpnuqgvadf3p6qfmj34r4epdi.apps.googleusercontent.com',
    iosClientId: '773220965064-rgs5o4mqi0eie1n3ish0uueopknn0713.apps.googleusercontent.com',
    iosBundleId: 'com.myapp.kokzakiAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyJrC0BrNIuzt0Lk2Yu92NOgADKgYZvXk',
    appId: '1:773220965064:ios:9068cd83554ad2042123fd',
    messagingSenderId: '773220965064',
    projectId: 'grocery-80ead',
    storageBucket: 'grocery-80ead.appspot.com',
    androidClientId: '773220965064-677sbjilpnuqgvadf3p6qfmj34r4epdi.apps.googleusercontent.com',
    iosClientId: '773220965064-n83iqc377nf570upkm4eq6c92t41bmdg.apps.googleusercontent.com',
    iosBundleId: 'com.myapp.kokzakiAdminPanel.RunnerTests',
  );
}
